#!/bin/bash

rm -f $0
echo -e "###############################################################################\nBanhammer20k run on `date`\n###############################################################################\n"
echo -e "Flushing iptables.\n"
>dropped
iptables -F DROPSPAMMERS 2>/dev/null
iptables -X DROPSPAMMERS 2>/dev/null
iptables -N DROPSPAMMERS 2>/dev/null
echo -e "\nLooking for bot addresses in domlogs. This may take a while.\n"
comm -12 <(wget -qO- http://listed.privatesystems.net/latest/stopforumspam.com/bannedips.csv|sort) <(find /usr/local/apache/domlogs /var/www/vhosts/*/statistics/logs/access_log /var/log/httpd/domains -type f 2>/dev/null|egrep -v 'bytes_log|ftpx|error\.log'|xargs tail -n 20000|awk '{print $1}'|egrep -v '\=|[a-zA-Z]|0-9]{4}'|sort|uniq)|xargs -I % sh -c 'iptables -A DROPSPAMMERS -j DROP -s %; echo "Dropped %";'|tee dropped
wc -l dropped
rm -f dropped
echo -e "\nDone scanning.\n"


